In [ ]:
# !pip install rouge_score datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
bart = pd.read_csv('bart.csv')
t5 = pd.read_csv('t5.csv')
pegasus = pd.read_csv('pegasus.csv')

In [3]:
df = pd.read_csv('bart.csv')

In [4]:
bart.columns = ['Summary', 'Text', 'bart']
t5.columns = ['Summary', 'Text', 't5']
pegasus.columns = ['Summary', 'Text', 'pegasus']

In [6]:
df = df[['Text', 'Summary']]

In [8]:
df['bart'] = bart['bart']
df['t5'] = t5['t5']
df['pegasus'] = pegasus['pegasus']

In [10]:
from nltk.translate.bleu_score import sentence_bleu
from tqdm import tqdm
from datasets import load_dataset, load_metric

In [11]:
df

,Text,Summary,bart,t5,pegasus
0,The Daman and Diu administration on Wednesday ...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday...,circular asked women staff to tie rakhis to th...,A Hindu festival that is often used as a polit...
1,"From her special numbers to TV?appearances, Bo...",Malaika Arora slammed an Instagram user who tr...,"A follower of Malaika Arora Khan, who has bee...",Malaika Arora Khan made her debut in the Hindi...,Malaika Arora Khan has responded to a troll on...
2,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Scienc...,the Indira Gandhi Institute of Medical Science...,A medical institute in Bihar has changed its r...
3,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,A++ terrorist Abu Dujana was killed in an enc...,dujana was among the top 10 terrorists identif...,A top militant killed in an encounter in India...
4,Hotels in Mumbai and other Indian cities are t...,Hotels in Maharashtra will train their staff t...,A hotel alumni group in Mumbai has launched a...,hotel staff to train to spot signs of sex traf...,Hotels in India are being trained to spot sign...
5,An alleged suspect in a kidnapping case was fo...,A 32-year-old man on Wednesday was found hangi...,A 32-year-old man was found dead inside the w...,an alleged suspect was found hanging in the wa...,The police have denied that the man who was fo...
6,"In an interesting ruling, the Delhi high court...",The Delhi High Court reduced the compensation ...,Delhi High Court reduced the compensation awa...,a trial court reduced the compensation awarded...,jaywalkers who suddenly appear on the road pos...
7,A 60-year old Dalit woman was allegedly lynch...,A 60-year old Dalit woman was allegedly lynche...,A 60-year-old Dalit woman was allegedly lynch...,"maan Devi, 60, was allegedly lynched in Agra a...",Police in India are on alert after a woman was...
8,Two years after a helicopter crash near the Bo...,An inquiry by the Aircraft Accident Investigat...,A two-year-old helicopter crash near the Bomb...,the chopper was flying at a critically low hei...,"The report mentioned that the instructor, Capt..."
9,"It sounds like satire, but make no mistake: at...",The Congress party has opened a bank called 'S...,The Congress Party has opened a 'State Bank o...,Congress has opened a 'State Bank of Tomato' i...,"""Tomatoes are not real money, they are gold."""
10,The Food Safety and Standards Authority of Ind...,India's food regulator Food Safety and Standar...,The Food Safety and Standards Authority of In...,FSSAI is in the process of creating a network ...,India is planning to introduce a new food bank...
11,"Bharti Sharma, mother of the 16-year-old boy w...","The mother of Harshit Sharma, the class 12 Cha...",The 16-year-old boy who got a job offer from ...,the mother of the 16-year-old boy made headlin...,Harshit Sharma?s mother has said the hoax job ...
12,Only 26 malls and commercial centres on Mehrau...,Municipal Corporation of Gurugram on Wednesday...,The Municipal Corporation of Gurugram has ann...,only 26 malls and commercial centres will offe...,The list of commercial centres and malls in Gu...
13,Scientists have modified human embryos to remo...,"Scientists, for the first time, successfully f...",Scientists have modified human embryos to rem...,a new study of genetic mutations in human embr...,The world?s first baby has been born using a t...
14,"As many as 2,297 residential buildings under t...",A Union Minister of State for Home Affairs inf...,"As many as 2,297 residential buildings under ...","as many as 2,297 residential buildings under t...","More than 2,000 buildings in Delhi have been i..."
15,The Supreme Court on Thursday refused to stay ...,The Supreme Court today refused to stay the ex...,The Supreme Court on Thursday refused to stay...,the bench of justices agreed to examine the co...,The Congress has moved the Supreme Court again...
16,A 24-year-old Indian athlete has been indicted...,"Tanveer Hussain, a 24-year-old Indian athlete ...",A 24-year-old Indian athlete Tanveer Hussain ...,"Tanveer Hussain, 24, was indicted last week on...",The case of Tanveer Hussain has sparked a deba...
17,"New Delhi, Aug 2 (PTI) Bomb squads and canine ...",Bomb squads and canine teams were rushed to ch...,A suspect object was recovered at the cargo h...,bomb squads and canine teams rushed in to chec...,A security alert at the Indira Gandhi Internat...
18,Bihar Health Minister Mangal Pandey has defend...,"Defending the IGIMS marital declaration form, ...",Bihar Health Minister Mangal Pandey has defen...,a controversial questionnaire was put out by I...,A medical institute in Bihar has been criticis...
19,A Norwegian anti-immigrant group has been roun...,The members of a Norwegian anti-immigrant grou...,A Norwegian anti-immigrant group's members ap...,a photo of a group of women wearing burqas was...,All photographs Johan Slttavik.
20,"In a bizarre medical condition, a newborn baby...",A newborn boy in Maharashtra's Thane was found...,"A 19-year-old woman from Mumbra, Thane, Mahar...",a newborn baby was found to be ?pregnant? with...,Doctors in India have successfully removed a p...
21,Dozens of street vendors will have to take the...,The North Delhi Municipal Corporation has said...,Delhi's Delhi Municipal Council has decided t...,street vendors will have to take their wares e...,The traffic jam outside two major hospitals in...
22,"Over 400 farmers, including women, took to the...",Over 400 farmers from Greater Noida and adjoin...,A total of 39 farmers were arrested on Friday...,farmers marched demanding a hike in compensati...,The Gautam Budh Nagar district administration ...
23,Newly released data and photos show how shocki...,Investigators have released pictures showing h...,A Air Canada jet was flying at 59ft above gro...,pilots mistook the taxiway for the runway next...,Investigators are looking into whether pilot e...
24,Two people were killed when a light plane made...,"Two sunbathers, a 56-year-old man and an eight...",A 56-year-old man and an eight-year old girl ...,"two sunbathers, a 56-year-old man and a girl, ...",All images are copyrighted.
25,The Saudi-led coalition fighting in Yemen is o...,The Saudi-led coalition in Yemen is blocking d...,"Auke Lootsma, the country director of the UN ...","auke Lootsma, the director of the UN Developme...",The Saudi-led coalition fighting in Yemen is o...
26,The US Air Force successfully launched an unar...,The US Air Force on Wednesday successfully lau...,The Minuteman 3 missile launched at 2:10 a.m....,the u.s. air force successfully launched an un...,All photographs by Air Force.
27,The remains of a German hiker who disappeared ...,"The remains of a German hiker, who disappeared...",The body of a German hiker who disappeared wh...,the remains of a german hiker have been found ...,All images are copyrighted.
28,Yesteryear superstar Dilip Kumar was rushed to...,Veteran actor Dilip Kumar has been admitted to...,The 94-year-old actor Dilip Kumar was admitte...,the actor is stable and currently recovering i...,Veteran Bollywood actor Dilip Kumar is recover...
29,The Mangrove Society of India (MSI) has put t...,The Mangrove Society of India has listed Mumba...,India has 3% of the world's mangrove cover an...,mangroves are one of the largest mangrove fore...,India?s mangroves are set to become an interna...
30,Jammu and Kashmir police approached the Pakist...,Jammu and Kashmir Police have approached the P...,Jammu and Kashmir police on Tuesday approache...,police ask Pakistan high commission to claim t...,Police in Indian-administered Kashmir have ask...
31,Slain Lashkar-e-Taiba (LeT) commander Abu Duja...,"Abu Ismail, mastermind of the Amarnath Yatra a...","LeT commander Abu Ismail, who was killed in a...",Ismail will be the new Kashmir division chief ...,The Indian government has replaced a top milit...
32,US President Donald Trump has called the White...,"Explaining his frequent visits to golf clubs, ...",US President Donald Trump has reportedly call...,the white house did not respond to a request f...,The White House has not responded to a request...
33,A suspected British prankster appears to have ...,"A self-styled email prankster, known as @SINON...","The man, who goes by the Twitter handle @SINO...","the man, who goes by the Twitter handle @SINON...",As Donald Trump?s White House undergoes a shak...
34,A GP who practised in east London has been cha...,"A UK-based doctor, Manish Shah, has been charg...","GP Manish Shah, 47, has been charged with 118...",Manish Shah is charged with 65 counts of assau...,All images are copyrighted.
35,President Donald Trump?s son-in-law says the T...,US President Donald Trump's campaign could not...,"The President's son-in-law Jared Kushner, a s...",a senior adviser to the president says the Tru...,President Donald Trump?s son-in-law says the T...
36,A woman parliamentarian of Imran Khan?s Pakist...,A woman lawmaker of Pakistan Tehreek-e-Insaf (...,"Ayesha Gulalai, a member of Imran Khan's Paki...",a woman parliamentarian of Imran Khan's Pakist...,All images are copyrighted.
37,"London, Aug 1 (PTI) Renowned Harry Potter auth...",Harry Potter author JK Rowling has apologised ...,The Harry Potter author J K Rowling has apolo...,"author apologises ""unreserved"" for wrongly acc...","""I very clearly projected my own sensitivities..."
38,A recent study has found a substantial presenc...,"Substantial presence of PM1, reportedly the mo...",A recent study has found a substantial presen...,a study has found a substantial presence in th...,"The Indian capital, Delhi, is a city of smog."
39,The Ghaziabad police arrested three persons an...,The Ghaziabad Police has booked 14 people incl...,Ghaziabad police on Monday arrested three Con...,police have arrested three people and lodged a...,Police have arrested several Congress leaders ...
40,A Republican senator said Tuesday that US Pres...,Republican Senator Lindsey Graham has said tha...,US President Donald Trump has told Lindsey Gr...,a foreign policy hawk said he would go to war ...,The United States is preparing a military resp...
41,After accusing director Anees Bazme and his fr...,"Comedian Sunil Pal, in a Facebook video, has a...",Comedian Sunil Pal has accused director Anees...,anees bazmee and his friend Mayur barot were a...,Comedian Sunil Pal is planning to take legal a...
42,The Daman and Diu administration on Wednesday ...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday...,the circular was withdrawn by the daman and di...,A Hindu festival that is often used as a polit...
43,The United States on Wednesday officially set ...,The United States on Wednesday announced that ...,The United States on Wednesday officially set...,the ban is to remain in effect for one year un...,"All photographs courtesy of AFP, EPA, Getty Im..."
44,"New Delhi, Aug 1 (PTI) Finance Minister Arun J...",Finance Minister Arun Jaitley has said that a ...,A group of ministers headed by Finance Minist...,"a ""proper decision"" would be taken on what Air...",The government is considering the sale of a ma...
45,"The AA has fired its boss, Bob Mackenzie, for ...",UK roadside repair firm AA on Tuesday lost ove...,AA has announced that Bob Mackenzie has been ...,a spokesperson for the roadside repair company...,"The boss of the AA has been sacked for ""gross ..."
46,"Life OK, which is geared up to re-brand itself...","According to reports, yoga guru Ramdev and act...","Life OK, which is set to re-brand itself as S...",life OK has collaborated with Colosceum Media ...,The Indian television industry is gearing up f...
47,Naseeruddin Shah has watched the film Lipstick...,"Actor Naseeruddin Shah, while talking about th...",Naseeruddin Shah has seen the film Lipstick U...,the film's success has done is that it has sho...,"In an interview to HT, Naseeruddin Shah explai..."
48,"Bollywood star Amitabh Bachchan, who is curren...",Amitabh Bachchan has said that the opportunity...,Aamir Khan's son Amitabh Bachchan has said th...,"Amitabh Bachchan, 74, is currently shooting fo...",All images are copyrighted.

In [12]:
for i, row in tqdm(df[:].iterrows()):
    bart = sentence_bleu([row['Summary'].split()], row['bart'].split())
    t5 = sentence_bleu([row['Summary'].split()], row['t5'].split())
    pegasus = sentence_bleu([row['Summary'].split()], row['pegasus'].split())
    if((bart>=t5) & (bart>=pegasus)):
        df.at[i, 'final'] = row['bart']
    elif((t5>=bart) & (t5>=pegasus)):
        df.at[i, 'final'] = row['t5']
    elif((pegasus>=bart) & (pegasus>=t5)):
        df.at[i, 'final'] = row['pegasus']

0it [00:00, ?it/s]c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
49it [00:00, 398.19it/s]

In [13]:
metric = load_metric("rouge")

In [15]:
df

,Text,Summary,bart,t5,pegasus,final
0,The Daman and Diu administration on Wednesday ...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday...,circular asked women staff to tie rakhis to th...,A Hindu festival that is often used as a polit...,The Daman and Diu administration on Wednesday...
1,"From her special numbers to TV?appearances, Bo...",Malaika Arora slammed an Instagram user who tr...,"A follower of Malaika Arora Khan, who has bee...",Malaika Arora Khan made her debut in the Hindi...,Malaika Arora Khan has responded to a troll on...,"A follower of Malaika Arora Khan, who has bee..."
2,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Scienc...,the Indira Gandhi Institute of Medical Science...,A medical institute in Bihar has changed its r...,The Indira Gandhi Institute of Medical Scienc...
3,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,A++ terrorist Abu Dujana was killed in an enc...,dujana was among the top 10 terrorists identif...,A top militant killed in an encounter in India...,A++ terrorist Abu Dujana was killed in an enc...
4,Hotels in Mumbai and other Indian cities are t...,Hotels in Maharashtra will train their staff t...,A hotel alumni group in Mumbai has launched a...,hotel staff to train to spot signs of sex traf...,Hotels in India are being trained to spot sign...,hotel staff to train to spot signs of sex traf...
5,An alleged suspect in a kidnapping case was fo...,A 32-year-old man on Wednesday was found hangi...,A 32-year-old man was found dead inside the w...,an alleged suspect was found hanging in the wa...,The police have denied that the man who was fo...,A 32-year-old man was found dead inside the w...
6,"In an interesting ruling, the Delhi high court...",The Delhi High Court reduced the compensation ...,Delhi High Court reduced the compensation awa...,a trial court reduced the compensation awarded...,jaywalkers who suddenly appear on the road pos...,Delhi High Court reduced the compensation awa...
7,A 60-year old Dalit woman was allegedly lynch...,A 60-year old Dalit woman was allegedly lynche...,A 60-year-old Dalit woman was allegedly lynch...,"maan Devi, 60, was allegedly lynched in Agra a...",Police in India are on alert after a woman was...,"maan Devi, 60, was allegedly lynched in Agra a..."
8,Two years after a helicopter crash near the Bo...,An inquiry by the Aircraft Accident Investigat...,A two-year-old helicopter crash near the Bomb...,the chopper was flying at a critically low hei...,"The report mentioned that the instructor, Capt...",A two-year-old helicopter crash near the Bomb...
9,"It sounds like satire, but make no mistake: at...",The Congress party has opened a bank called 'S...,The Congress Party has opened a 'State Bank o...,Congress has opened a 'State Bank of Tomato' i...,"""Tomatoes are not real money, they are gold.""",Congress has opened a 'State Bank of Tomato' i...
10,The Food Safety and Standards Authority of Ind...,India's food regulator Food Safety and Standar...,The Food Safety and Standards Authority of In...,FSSAI is in the process of creating a network ...,India is planning to introduce a new food bank...,The Food Safety and Standards Authority of In...
11,"Bharti Sharma, mother of the 16-year-old boy w...","The mother of Harshit Sharma, the class 12 Cha...",The 16-year-old boy who got a job offer from ...,the mother of the 16-year-old boy made headlin...,Harshit Sharma?s mother has said the hoax job ...,The 16-year-old boy who got a job offer from ...
12,Only 26 malls and commercial centres on Mehrau...,Municipal Corporation of Gurugram on Wednesday...,The Municipal Corporation of Gurugram has ann...,only 26 malls and commercial centres will offe...,The list of commercial centres and malls in Gu...,The Municipal Corporation of Gurugram has ann...
13,Scientists have modified human embryos to remo...,"Scientists, for the first time, successfully f...",Scientists have modified human embryos to rem...,a new study of genetic mutations in human embr...,The world?s first baby has been born using a t...,Scientists have modified human embryos to rem...
14,"As many as 2,297 residential buildings under t...",A Union Minister of State for Home Affairs inf...,"As many as 2,297 residential buildings under ...","as many as 2,297 residential buildings under t...","More than 2,000 buildings in Delhi have been i...","As many as 2,297 residential buildings under ..."
15,The Supreme Court on Thursday refused to stay ...,The Supreme Court today refused to stay the ex...,The Supreme Court on Thursday refused to stay...,the bench of justices agreed to examine the co...,The Congress has moved the Supreme Court again...,The Supreme Court on Thursday refused to stay...
16,A 24-year-old Indian athlete has been indicted...,"Tanveer Hussain, a 24-year-old Indian athlete ...",A 24-year-old Indian athlete Tanveer Hussain ...,"Tanveer Hussain, 24, was indicted last week on...",The case of Tanveer Hussain has sparked a deba...,"Tanveer Hussain, 24, was indicted last week on..."
17,"New Delhi, Aug 2 (PTI) Bomb squads and canine ...",Bomb squads and canine teams were rushed to ch...,A suspect object was recovered at the cargo h...,bomb squads and canine teams rushed in to chec...,A security alert at the Indira Gandhi Internat...,bomb squads and canine teams rushed in to chec...
18,Bihar Health Minister Mangal Pandey has defend...,"Defending the IGIMS marital declaration form, ...",Bihar Health Minister Mangal Pandey has defen...,a controversial questionnaire was put out by I...,A medical institute in Bihar has been criticis...,Bihar Health Minister Mangal Pandey has defen...
19,A Norwegian anti-immigrant group has been roun...,The members of a Norwegian anti-immigrant grou...,A Norwegian anti-immigrant group's members ap...,a photo of a group of women wearing burqas was...,All photographs Johan Slttavik.,A Norwegian anti-immigrant group's members ap...
20,"In a bizarre medical condition, a newborn baby...",A newborn boy in Maharashtra's Thane was found...,"A 19-year-old woman from Mumbra, Thane, Mahar...",a newborn baby was found to be ?pregnant? with...,Doctors in India have successfully removed a p...,a newborn baby was found to be ?pregnant? with...
21,Dozens of street vendors will have to take the...,The North Delhi Municipal Corporation has said...,Delhi's Delhi Municipal Council has decided t...,street vendors will have to take their wares e...,The traffic jam outside two major hospitals in...,Delhi's Delhi Municipal Council has decided t...
22,"Over 400 farmers, including women, took to the...",Over 400 farmers from Greater Noida and adjoin...,A total of 39 farmers were arrested on Friday...,farmers marched demanding a hike in compensati...,The Gautam Budh Nagar district administration ...,farmers marched demanding a hike in compensati...
23,Newly released data and photos show how shocki...,Investigators have released pictures showing h...,A Air Canada jet was flying at 59ft above gro...,pilots mistook the taxiway for the runway next...,Investigators are looking into whether pilot e...,A Air Canada jet was flying at 59ft above gro...
24,Two people were killed when a light plane made...,"Two sunbathers, a 56-year-old man and an eight...",A 56-year-old man and an eight-year old girl ...,"two sunbathers, a 56-year-old man and a girl, ...",All images are copyrighted.,A 56-year-old man and an eight-year old girl ...
25,The Saudi-led coalition fighting in Yemen is o...,The Saudi-led coalition in Yemen is blocking d...,"Auke Lootsma, the country director of the UN ...","auke Lootsma, the director of the UN Developme...",The Saudi-led coalition fighting in Yemen is o...,"Auke Lootsma, the country director of the UN ..."
26,The US Air Force successfully launched an unar...,The US Air Force on Wednesday successfully lau...,The Minuteman 3 missile launched at 2:10 a.m....,the u.s. air force successfully launched an un...,All photographs by Air Force.,The Minuteman 3 missile launched at 2:10 a.m....
27,The remains of a German hiker who disappeared ...,"The remains of a German hiker, who disappeared...",The body of a German hiker who disappeared wh...,the remains of a german hiker have been found ...,All images are copyrighted.,The body of a German hiker who disappeared wh...
28,Yesteryear superstar Dilip Kumar was rushed to...,Veteran actor Dilip Kumar has been admitted to...,The 94-year-old actor Dilip Kumar was admitte...,the actor is stable and currently recovering i...,Veteran Bollywood actor Dilip Kumar is recover...,The 94-year-old actor Dilip Kumar was admitte...
29,The Mangrove Society of India (MSI) has put t...,The Mangrove Society of India has listed Mumba...,India has 3% of the world's mangrove cover an...,mangroves are one of the largest mangrove fore...,India?s mangroves are set to become an interna...,India has 3% of the world's mangrove cover an...
30,Jammu and Kashmir police approached the Pakist...,Jammu and Kashmir Police have approached the P...,Jammu and Kashmir police on Tuesday approache...,police ask Pakistan high commission to claim t...,Police in Indian-administered Kashmir have ask...,Jammu and Kashmir police on Tuesday approache...
31,Slain Lashkar-e-Taiba (LeT) commander Abu Duja...,"Abu Ismail, mastermind of the Amarnath Yatra a...","LeT commander Abu Ismail, who was killed in a...",Ismail will be the new Kashmir division chief ...,The Indian government has replaced a top milit...,"LeT commander Abu Ismail, who was killed in a..."
32,US President Donald Trump has called the White...,"Explaining his frequent visits to golf clubs, ...",US President Donald Trump has reportedly call...,the white house did not respond to a request f...,The White House has not responded to a request...,US President Donald Trump has reportedly call...
33,A suspected British prankster appears to have ...,"A self-styled email prankster, known as @SINON...","The man, who goes by the Twitter handle @SINO...","the man, who goes by the Twitter handle @SINON...",As Donald Trump?s White House undergoes a shak...,"The man, who goes by the Twitter handle @SINO..."
34,A GP who practised in east London has been cha...,"A UK-based doctor, Manish Shah, has been charg...","GP Manish Shah, 47, has been charged with 118...",Manish Shah is charged with 65 counts of assau...,All images are copyrighted.,"GP Manish Shah, 47, has been charged with 118..."
35,President Donald Trump?s son-in-law says the T...,US President Donald Trump's campaign could not...,"The President's son-in-law Jared Kushner, a s...",a senior adviser to the president says the Tru...,President Donald Trump?s son-in-law says the T...,a senior adviser to the president says the Tru...
36,A woman parliamentarian of Imran Khan?s Pakist...,A woman lawmaker of Pakistan Tehreek-e-Insaf (...,"Ayesha Gulalai, a member of Imran Khan's Paki...",a woman parliamentarian of Imran Khan's Pakist...,All images are copyrighted.,a woman parliamentarian of Imran Khan's Pakist...
37,"London, Aug 1 (PTI) Renowned Harry Potter auth...",Harry Potter author JK Rowling has apologised ...,The Harry Potter author J K Rowling has apolo...,"author apologises ""unreserved"" for wrongly acc...","""I very clearly projected my own sensitivities...",The Harry Potter author J K Rowling has apolo...
38,A recent study has found a substantial presenc...,"Substantial presence of PM1, reportedly the mo...",A recent study has found a substantial presen...,a study has found a substantial presence in th...,"The Indian capital, Delhi, is a city of smog.",A recent study has found a substantial presen...
39,The Ghaziabad police arrested three persons an...,The Ghaziabad Police has booked 14 people incl...,Ghaziabad police on Monday arrested three Con...,police have arrested three people and lodged a...,Police have arrested several Congress leaders ...,Ghaziabad police on Monday arrested three Con...
40,A Republican senator said Tuesday that US Pres...,Republican Senator Lindsey Graham has said tha...,US President Donald Trump has told Lindsey Gr...,a foreign policy hawk said he would go to war ...,The United States is preparing a military resp...,US President Donald Trump has told Lindsey Gr...
41,After accusing director Anees Bazme and his fr...,"Comedian Sunil Pal, in a Facebook video, has a...",Comedian Sunil Pal has accused director Anees...,anees bazmee and his friend Mayur barot were a...,Comedian Sunil Pal is planning to take legal a...,Comedian Sunil Pal has accused director Anees...
42,The Daman and Diu administration on Wednesday ...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday...,the circular was withdrawn by the daman and di...,A Hindu festival that is often used as a polit...,The Daman and Diu administration on Wednesday...
43,The United States on Wednesday officially set ...,The United States on Wednesday announced that ...,The United States on Wednesday officially set...,the ban is to remain in effect for one year un...,"All photographs courtesy of AFP, EPA, Getty Im...",The United States on Wednesday officially set...
44,"New Delhi, Aug 1 (PTI) Finance Minister Arun J...",Finance Minister Arun Jaitley has said that a ...,A group of ministers headed by Finance Minist...,"a ""proper decision"" would be taken on what Air...",The government is considering the sale of a ma...,"a ""proper decision"" would be taken on what Air..."
45,"The AA has fired its boss, Bob Mackenzie, for ...",UK roadside repair firm AA on Tuesday lost ove...,AA has announced that Bob Mackenzie has been ...,a spokesperson for the roadside repair company...,"The boss of the AA has been sacked for ""gross ...",AA has announced that Bob Mackenzie has been ...
46,"Life OK, which is geared up to re-brand itself...","According to reports, yoga guru Ramdev and act...","Life OK, which is set to re-brand itself as S...",life OK has collaborated with Colosceum Media ...,The Indian television industry is gearing up f...,"Life OK, which is set to re-brand itself as S..."
47,Naseeruddin Shah has watched the film Lipstick...,"Actor Naseeruddin Shah, while talking about th...",Naseeruddin Shah has seen the film Lipstick U...,the film's success has done is that it has sho...,"In an interview to HT, Naseeruddin Shah explai...","In an interview to HT, Naseeruddin Shah explai..."
48,"Bollywood star Amitabh Bachchan, who is curren...",Amitabh Bachchan has said that the opportunity...,Aamir Khan's son Amitabh Bachchan has said th...,"Amitabh Bachchan, 74, is currently shooting fo...",All images are copyrighted.,Aamir Khan's son Amitabh Bachchan has said th...

In [14]:
results = metric.compute(predictions=df['final'],
                         references =df['Summary'])
print(results)

{'rouge1': AggregateScore(low=Score(precision=0.4396942928735906, recall=0.4697805402680139, fmeasure=0.44955493172229855), mid=Score(precision=0.4819845830185241, recall=0.5058171194540375, fmeasure=0.48444050964842444), high=Score(precision=0.516853554797118, recall=0.5436286627496695, fmeasure=0.5168717834501051)), 'rouge2': AggregateScore(low=Score(precision=0.21972578679146082, recall=0.23053142696158802, fmeasure=0.22236975228269926), mid=Score(precision=0.2590824746357765, recall=0.2687125764951781, fmeasure=0.2586369668082281), high=Score(precision=0.29649908555240767, recall=0.3068865073347572, fmeasure=0.29375264489757386)), 'rougeL': AggregateScore(low=Score(precision=0.31600202848595094, recall=0.3325486336901658, fmeasure=0.3208088327578448), mid=Score(precision=0.3537396049618172, recall=0.36771272204575955, fmeasure=0.35435779199402573), high=Score(precision=0.39347018125287375, recall=0.40490985038869753, fmeasure=0.3894891275489668)), 'rougeLsum': AggregateScore(low=Score(precision=0.31507619094390954, recall=0.3334211670379686, fmeasure=0.31969789931500087), mid=Score(precision=0.35351736726354366, recall=0.36713062711796063, fmeasure=0.3533281285877795), high=Score(precision=0.39333840380642704, recall=0.40717053578932494, fmeasure=0.3924042966136159))}

In [16]:
for key in ["rouge1", "rouge2", "rougeL"]:
    print(key, "low:", results[key].low.fmeasure)
    print(key, "mid:", results[key].mid.fmeasure)
    print(key, "high:", results[key].high.fmeasure, end="\n\n")

rouge1 low: 0.44955493172229855
rouge1 mid: 0.48444050964842444
rouge1 high: 0.5168717834501051

rouge2 low: 0.22236975228269926
rouge2 mid: 0.2586369668082281
rouge2 high: 0.29375264489757386

rougeL low: 0.3208088327578448
rougeL mid: 0.35435779199402573
rougeL high: 0.3894891275489668

In [17]:
bleu = []
for i, row in tqdm(df.iterrows()):
  bleu.append(sentence_bleu([row['Summary'].split()], row['final'].split()))

0it [00:00, ?it/s]c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
49it [00:00, 1126.12it/s]

In [18]:
print('bleu   :',   np.mean(bleu))

bleu   : 0.15084766988385523